### ISSUE TITLE
locale_t build errors since 20191129

### ISSUE THREAD

**Issue by nickwynja** [neomutt/neomutt#2269]
## Expected Behaviour

Build succeeds.

## Actual Behaviour

```
mx.c:1082:7: error: use of undeclared identifier 'locale_t'
      locale_t loc = newlocale(LC_TIME_MASK, "C", 0);
      ^
mx.c:1085:7: warning: implicit declaration of function 'strftime_l' is invalid in C99
      [-Wimplicit-function-declaration]
      strftime_l(buf, sizeof(buf), "%a %b %e %H:%M:%S %Y", &tm, loc);
      ^
mx.c:1085:65: error: use of undeclared identifier 'loc'
      strftime_l(buf, sizeof(buf), "%a %b %e %H:%M:%S %Y", &tm, loc);
                                                                ^
mx.c:1086:7: warning: implicit declaration of function 'freelocale' is invalid in C99
      [-Wimplicit-function-declaration]
      freelocale(loc);
      ^
mx.c:1086:18: error: use of undeclared identifier 'loc'
      freelocale(loc);
                 ^
```

## Steps to Reproduce

```
./configure  --notmuch --disable-doc --disable-nls --lmdb
sudo make
sudo make install
```

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

`20191129`. Related to code introduced in #2172

## Extra Info

* Operating System and its version
    * macOS 10.15.2
* Were you using multiple copies of NeoMutt at once?
* Were you using 'screen' or 'tmux'?
    * tmux 3.0a
* Is your email local (maildir) or remote (IMAP)?
    * maildir

**Comment by flatcap** [comment]
@jindraj Is this the problem you saw and fixed?

**Comment by jindraj** [comment]
Yep. Adding `--with-nls` solved it for me:
```
--with-nls=/usr/local/opt/gettext
```

**Comment by nickwynja** [comment]
Ah, great, that worked. Thank you! I believe I was previously using
`--disable-nls` because of some dependency issues I wasn't able to resolve but
this built fine now.
