### ISSUE TITLE
conditional format strings broken in 2024-04-25

### ISSUE THREAD

**Issue by emtiu** [neomutt/neomutt#4286]
## The situation

I've been using a set of highly complex conditional format strings since 2017. After setting them up, I never touched them again, **so I've completely forgotten how to read them and how they work** (sorry).

These are the format strings in question:
```
set index_format=" %<[y?%<[w?%<[d?%10[%H:%M]&%10[!%a %H:%M]>&%10[%d.%m. %Hh]>&%-10[%d.%m.%Y]> %18.18F %S %?M?◢ ?%s%* %?X? <%X>?%?M? [%M]?"
set sidebar_format="%B%*  %<n?\<%N\\>&%<N?[%N]&>>"
```

## Changes in 2024-04-16

When updating to 2024-04-16, there was just one minor hitch with `sidebar_format` when showing a folder with _1 new message_:
- Until 2024-03-29, the sidebar displayed `<1>`.
- In 2024-04-16, it displayed `<1\>` instead.

To fix this, i removed the double backslash from `sidebar_format`, meaning that I changed
```
set sidebar_format="%B%*  %<n?\<%N\\>&%<N?[%N]&>>"
```
into
```
set sidebar_format="%B%*  %<n?\<%N\>&%<N?[%N]&>>"
```

which fixed the issue.

## Changes in 2024-04-25
When launching 2024-04-25 with the format strings quoted above, I see the following error message:
```
/[…]/neomuttrc:114: Option index_format: Conditional expando is missing '&' or '?'
source: errors in /[…]/neomuttrc
```
(Line 114 in `neomuttrc` contains the `index_format` quoted above.)

After hitting a key, neomutt starts, **but the format strings are all broken, both in the sidebar and in the index**.

In the **sidebar**:
- all folders with no unread/new messages show `&>` after the name (before, there would be nothing there)
- folders with 1 unread message show `&[1]>` (before, it would display `[1]`)
- folders with 1 new message show `<1&[1]>` (before, it would display `<1>`, see above)

In the **index**, I don't even recognize the format anymore – maybe it reverts to the default?

Here's an example line from the index with 2024-04-25:
`3 r + Apr 25 sender@sender.se (395K) The Message Subject`

Here's the same line with 2024-04-16 (displayed correctly):
`25.04. 21h sender@sender.se r ◢ The Message Subject      [2]`

## What's happening?
As explained above, I have no idea (sorry).

Looking through the recent Issues in this repo, I might be experiencing #4259, #4278, or both.

Maybe there's some other useful thing for you to find here.

**Comment by ragu-manjegowda** [comment]
I am running into same issue, refraining from upgrading for now.

This is what I have and it works fine with `NeoMutt 20240329` 

```
folder-hook Inbox 'set index_format=" %4C %zc %zs %zt  | %-35.35L   %@attachment_info@  %?M10?~(%1M) ?%-30.50s %> %?Y?%Y ? %(!%a %d %h %H:%M)"'

index-format-hook attachment_info '~M text/calendar ~X > 0' ' '
index-format-hook attachment_info '~M text/calendar' "  "
index-format-hook attachment_info '~X > 0' "  "
index-format-hook attachment_info '~A' "   "

set attach_format = "%u%D  %T%-75.75d %<T?&   > %5s · %m/%M"
```

Similar to op, I have this since 3 years and no idea how they work.

**Comment by emtiu** [comment]
Sure, don't worry and take your time, these things happen :) Let me know if I can help further.

**Comment by ragu-manjegowda** [comment]
> @ragu-manjegowda Hmm... I'm surprised that ever worked :-)
> 
> There's a `10` (one zero) in the middle of your `set index_format...` that shouldn't be there. If I remove that, it works correctly in `2024-04-25`, `2024-04-16` and `2024-03-29` (I've also upgrade the `%M` and `%Y` conditions to use the modern `%<X?Y&Z>` format.
> 
> ```
> folder-hook Inbox 'set index_format=" %4C %zc %zs %zt  | %-35.35L   %@attachment_info@  %<M?~(%1M) >%-30.50s %> %<Y?%Y > %(!%a %d %h %H:%M)"'
> 
> index-format-hook attachment_info '~M text/calendar ~X > 0' ' '
> index-format-hook attachment_info '~M text/calendar' "  "
> index-format-hook attachment_info '~X > 0' "  "
> index-format-hook attachment_info '~A' "   "
> 
> set attach_format = "%u%D  %T%-75.75d %<T?&   > %5s · %m/%M"
> ```

Thank you so much :) You are the best!

**Comment by Tonus1** [comment]
Just hitted something similar.

This worked since several years and broke in last 2024-04-25 version :
```
set index_format="%4C|%=11y| %<[y?%<[m?%<[d?%-10.10[%H:%M]&%-10.10[%d %a]>&%-10.10[%d %b]>&%-10.10[%b %Y]> | %-25.25L|%?X?A&-?| %Z |%?M?#%-2.2M >>>&? %s%> |%=8c"
```

The `>>>` seems to be the culprit as changed with `···` like this worked :
```
set index_format="%4C|%=11y| %<[y?%<[m?%<[d?%-10.10[%H:%M]&%-10.10[%d %a]>&%-10.10[%d %b]>&%-10.10[%b %Y]> | %-25.25L|%?X?A&-?| %Z |%?M?#%-2.2M ···&? %s%>  |%=8c"
```

If that can help...

**Comment by flatcap** [comment]
@Tonus1 
Yes, that's the same problem.
The parser is working on a conditional `%<X?...` then finds some plain text `>` that looks like its end marker.

**Comment by anufrievroman** [comment]
I have the same error message but for this line:
```
set status_format = " %f • %l • %m messages%?n? • %n new ?%?d? • %d to delete ?%?t?"
```

**Comment by Tonus1** [comment]
Would you try to test without the `•` ?

**Comment by emtiu** [comment]
Just a gentle reminder that this issue is still present in [20241002](https://github.com/neomutt/neomutt/releases/tag/20241002), and it's preventing me from upgrading.

Is there any way we can help further?

**Comment by Tonus1** [comment]
First step would be to have the file wich has the parsing command/ regex

**Comment by emtiu** [comment]
A viable **workaround** (just tested with 20241002) is to remove plaintext `<` and `>` characters from the format strings and replacing them e.g. with `{` and `}`.

In my case, this meant changing:
```
set index_format=" %<[y?%<[w?%<[d?%10[%H:%M]&%10[!%a %H:%M]>&%10[%d.%m. %Hh]>&%-10[%d.%m.%Y]> %18.18F %S %?M?◢ ?%s%* %?X? <%X>?%?M? [%M]?"
set sidebar_format="%B%*  %<n?\<%N\>&%<N?[%N]&>>"
```

into:
```
set index_format=" %<[y?%<[w?%<[d?%10[%H:%M]&%10[!%a %H:%M]>&%10[%d.%m. %Hh]>&%-10[%d.%m.%Y]> %18.18F %S %?M?◢ ?%s%* %?X? {%X}?%?M? [%M]?"
set sidebar_format="%B%*  %<n?{%N}&%<N?[%N]&>>"
```

**Comment by flatcap** [comment]
Thanks for your patience.
I _was_ working on a fix, but then disappeared on a 3 month hiking expedition :-)
I'll make sure it fixed for the next release.

**Comment by emtiu** [comment]
Thank for your work to fix this! I tried to build your code from #4423, but I ran into a build failure:
```
In file included from debug/names_expando.c:32:
./autocrypt/lib.h:96:10: fatal error: 'sqlite3.h' file not found
   96 | #include <sqlite3.h>
      |          ^~~~~~~~~~~
```

I traced the problem to this line, introduced in f67006bd165c2da8054496bc60f4b0556152f57a:

https://github.com/neomutt/neomutt/blob/7abe5c0b13f436cca7b7d1459540e22b9b7b5c15/debug/names_expando.c#L32

I moved that include line into the `ifdef`-codeblock where I thought it probably belongs, a few lines below:

https://github.com/neomutt/neomutt/blob/7abe5c0b13f436cca7b7d1459540e22b9b7b5c15/debug/names_expando.c#L52-L54

Having done that, your code from #4423 build fine, and: **My expando code works ✅🥳**

For reference, here's the patch I used to fix the build:
```
--- debug/names_expando.c.orig	2024-11-01 09:10:26 UTC
+++ debug/names_expando.c
@@ -29,7 +29,6 @@
 #include "conn/lib.h"
 #include "gui/lib.h"
 #include "attach/lib.h"
-#include "autocrypt/lib.h"
 #include "browser/lib.h"
 #include "compmbox/lib.h"
 #include "expando/lib.h"
@@ -50,6 +49,7 @@
 #include "ncrypt/crypt_gpgme.h"
 #endif
 #ifdef USE_AUTOCRYPT
+#include "autocrypt/lib.h"
 #include "autocrypt/private.h"
 #endif
```

**Comment by flatcap** [comment]
@emtiu
Great!  Glad it's working.  Thanks!
And, oops!  Thanks for the fix.  The debug code is like the Wild West!

**Comment by mgedmin** [comment]
> And, oops! Thanks for the fix. The debug code is like the Wild West!

That wasn't me ;)
