### ISSUE TITLE
smtp_url: password cannot contain a question mark

### ISSUE THREAD

**Issue by knezi** [neomutt/neomutt#1043]
## bug report

* Expected behavior
Neomutt says the smtp_url is incorrect when sending an e-mail.
* Actual behavior
The url is correct.
* Steps to reproduce
Set in `.muttrc`:

```set smtp_url=smtps://"aaa":"AA?"@server```

Nothing else is needed, this is the whole config file causing the problem.

* Used program versions
Bisected, the first bad commit is https://github.com/neomutt/neomutt/commit/4ac1c81ed710c8b27dc23821330b2005f7122214
* Operating System and its version
Archlinux, x86_64

**Comment by bazzinotti** [comment]
Try
`set smtp_url="smtps://aaa:AA?@server"`

**Comment by flatcap** [comment]
Thanks for the bisect, @knezi

**Comment by flatcap** [comment]
A quick look at the code shows that the variable is being stored correctly.
It's the url parsing, when you come to send, that's going wrong.
No amount of escaping in the config file can work around this.

The problem starts here:
https://github.com/neomutt/neomutt/blob/74922c787a4efae9b8db9b497b680f073050c217/url.c#L177-L183

**Comment by flatcap** [comment]
@knezi Please can test the branch: [issue/1043](https://github.com/neomutt/neomutt/tree/issue%2F1043)

**Comment by knezi** [comment]
Wow, that was fast. I did `./configure && make` and it fails with:

```
url.c: In function ‘url_parse’:
url.c:178:21: error: ‘U_NOTMUCH’ undeclared (first use in this function)
   if ((u->scheme == U_NOTMUCH) || (u->scheme == U_MAILTO))
```

Running `./configure --notmuch && make` works and solves the problem. I cannot confirm if it really sends the e-mail, because not everything needed is included in the built (for instance SSL support). How is neomutt built for production? Simply `./configure --everything`?

Also, when I run `neomutt "mailto:aa"` I get SIGSEV. However, it might be just some missing dependency??
Anyway, output of GDB:

```
GNU gdb (GDB) 8.0.1
(gdb) run "mailto:A"
Starting program: /tmp/neomutt/neomutt "mailto:A"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Thread 1 "neomutt" received signal SIGSEGV, Segmentation fault.
mutt_rfc2047_decode (pd=pd@entry=0x555555950d20) at mutt/rfc2047.c:678
678	  while (*s)
(gdb) backtrace
#0  0x0000555555605930 in mutt_rfc2047_decode (pd=pd@entry=0x555555950d20) at mutt/rfc2047.c:678
#1  0x00005555555f5fe8 in url_parse_mailto (e=0x555555950ca0, body=0x7fffffffdd20, src=<optimized out>)
    at url.c:435
#2  0x000055555556d376 in main (argc=2, argv=0x7fffffffe538, env=<optimized out>) at main.c:568
```

**Comment by flatcap** [comment]
>  it fails with

Ah... Many of the constants aren't conditional.  That'll teach me to not check :-)
I've pushed a build fix for when Notmuch isn't enabled.

> works and solves the problem

Great.

> How is neomutt built for production?

That tends to depend on the distro and their choice of defaults.
We've changed the build to include more by default, so there's less variability now.

Specifically, for you, for Arch, their defaults are set here:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/neomutt

>  `--everything`?

That option is aimed at developers.
Not many people need to build all 6 database backends.

>  I get SIGSEV

Hmm... Thanks.  That's something new.  I'll investigate and push a fix, shortly.

**Comment by flatcap** [comment]
OK, the third commit should fix the crash.
Let me know if you have any other questions/trouble.

**Comment by knezi** [comment]
Thank you for the fix. Everything seems to be working now. I'd like to start coding on neomutt - namely Forgotten Attachment Improvement from https://www.neomutt.org/2016/10/07/news. Can you help me with it?

**Comment by flatcap** [comment]
> I'd like to start coding on neomutt

Brilliant.

> Forgotten Attachment Improvement...

That list is done, but I have some other 'easy' tasks.

> Can you help me with it?

Absolutely.
I'm in our IRC channel most days, most of the time.
We can find you a challenge that you like the sound of and help you get started.

Thanks :-)

**Comment by knezi** [comment]
Nice, it's been already implemented. Great, I'll go there.
