### ISSUE TITLE
Unable to compile with ---gpgme when using libgpg-error v1.33

### ISSUE THREAD

**Issue by Austin-Ray** [neomutt/neomutt#1493]
Arch Linux bumped their `libgpg-error` package to `1.33`, and upon installation, I am no longer able to  compile `neomutt` with `--gpgme`.

It produces the following error:
```
/usr/bin/ld: libncrypt.a(crypt_gpgme.o): undefined reference to symbol 'gpgrt_cmp_version@@GPG_ERROR_1.0'
/usr/bin/ld: /usr/lib/libgpg-error.so.0: error adding symbols: DSO missing from command line
```
`git bisect` yielded 3b0cec02a as the offending commit.

Since 3b0cec02a is a commit from upstream `mutt`, I tried compiling `mutt` and was able to do so successfully. 

I verified the installed copy of `gpg-error.h` included `gpgrt_cmp_version(...)`, which it did.

This leads to believe that the error is either with our `configure` tool or Arch Linux's packaging; however, I built and install `libgpg-error` from source and the issue was not resolved.

**Comment by flatcap** [comment]
If the 'gpgme' devel library is installed, I think it's likely that the 'gpg-error' devel library will be too.  That would mean we could simply add: `define-append LIBS -lgpg-error` (near the end):

https://github.com/neomutt/neomutt/blob/2949d769228ad5b99948a2b64be1b73ef81dd78f/auto.def#L366-L399

**Comment by vinpublic** [comment]
mutt uses gpgme's m4 to determine CFLAGS + LDFLAGS, that's why it wasn't affected. can autosetup do the same here?

**Comment by flatcap** [comment]
I've made it a bit smarter.
It looks for the version number, `GPGRT_VERSION_NUMBER`, in `gpg-error.h`.
If it's >= 1.33, it'll add `-lgpg-error`

https://github.com/neomutt/neomutt/blob/cb0cd64ef6e81ac8033d08739d4dde1704a323d5/auto.def#L392-L401
