### ISSUE TITLE
Can't compile with --notmuch

### ISSUE THREAD

**Issue by hvkls** [neomutt/neomutt#1750]
## Expected Behaviour

No compilation error

## Actual Behaviour

```
Undefined symbols for architecture x86_64:
  "_notmuch_database_begin_atomic", referenced from:
      _nm_db_trans_begin in libnotmuch.a(nm_db.o)
  "_notmuch_database_destroy", referenced from:
      _nm_db_release in libnotmuch.a(nm_db.o)
      _nm_db_free in libnotmuch.a(nm_db.o)
      _nm_db_longrun_done in libnotmuch.a(nm_db.o)
      _nm_db_debug_check in libnotmuch.a(nm_db.o)
  "_notmuch_database_end_atomic", referenced from:
      _nm_db_trans_end in libnotmuch.a(nm_db.o)
  "_notmuch_database_find_message", referenced from:
      _nm_read_entire_thread in libnotmuch.a(mutt_notmuch.o)
      _nm_tags_commit in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_database_find_message_by_filename", referenced from:
      _rename_filename in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_sync in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_database_get_all_tags", referenced from:
      _nm_get_all_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_database_index_file", referenced from:
      _rename_filename in libnotmuch.a(mutt_notmuch.o)
      _nm_record_message in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_database_open_verbose", referenced from:
      _nm_db_do_open in libnotmuch.a(nm_db.o)
  "_notmuch_database_remove_message", referenced from:
      _rename_filename in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_sync in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_filenames_get", referenced from:
      _rename_filename in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_check in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_sync in libnotmuch.a(mutt_notmuch.o)
      _append_message in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_filenames_move_to_next", referenced from:
      _rename_filename in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_check in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_sync in libnotmuch.a(mutt_notmuch.o)
      _append_message in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_filenames_valid", referenced from:
      _rename_filename in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_check in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_sync in libnotmuch.a(mutt_notmuch.o)
      _append_message in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_message_add_tag", referenced from:
      _update_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_message_destroy", referenced from:
      _read_threads_query in libnotmuch.a(mutt_notmuch.o)
      _rename_filename in libnotmuch.a(mutt_notmuch.o)
      _nm_record_message in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_open in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_check in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_sync in libnotmuch.a(mutt_notmuch.o)
      _append_replies in libnotmuch.a(mutt_notmuch.o)
      ...
  "_notmuch_message_freeze", referenced from:
      _update_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_message_get_filenames", referenced from:
      _rename_filename in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_check in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_sync in libnotmuch.a(mutt_notmuch.o)
      _append_message in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_message_get_message_id", referenced from:
      _append_message in libnotmuch.a(mutt_notmuch.o)
      _get_mutt_email in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_message_get_replies", referenced from:
      _append_replies in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_message_get_tags", referenced from:
      _update_tags in libnotmuch.a(mutt_notmuch.o)
      _update_email_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_message_get_thread_id", referenced from:
      _nm_read_entire_thread in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_message_maildir_flags_to_tags", referenced from:
      _rename_filename in libnotmuch.a(mutt_notmuch.o)
      _nm_record_message in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_message_remove_tag", referenced from:
      _update_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_message_thaw", referenced from:
      _update_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_messages_destroy", referenced from:
      _nm_message_is_still_queried in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_messages_get", referenced from:
      _read_threads_query in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_open in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_check in libnotmuch.a(mutt_notmuch.o)
      _append_replies in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_messages_move_to_next", referenced from:
      _read_threads_query in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_open in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_check in libnotmuch.a(mutt_notmuch.o)
      _append_replies in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_messages_valid", referenced from:
      _read_threads_query in libnotmuch.a(mutt_notmuch.o)
      _nm_message_is_still_queried in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_open in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_check in libnotmuch.a(mutt_notmuch.o)
      _append_replies in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_query_add_tag_exclude", referenced from:
      _apply_exclude_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_query_count_messages", referenced from:
      _count_query in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_query_create", referenced from:
      _nm_read_entire_thread in libnotmuch.a(mutt_notmuch.o)
      _nm_message_is_still_queried in libnotmuch.a(mutt_notmuch.o)
      _get_query in libnotmuch.a(mutt_notmuch.o)
      _count_query in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_query_destroy", referenced from:
      _nm_read_entire_thread in libnotmuch.a(mutt_notmuch.o)
      _nm_message_is_still_queried in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_open in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_check in libnotmuch.a(mutt_notmuch.o)
      _count_query in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_query_search_messages", referenced from:
      _nm_message_is_still_queried in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_open in libnotmuch.a(mutt_notmuch.o)
      _nm_mbox_check in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_query_search_threads", referenced from:
      _read_threads_query in libnotmuch.a(mutt_notmuch.o)
      _nm_message_is_still_queried in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_query_set_omit_excluded", referenced from:
      _apply_exclude_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_query_set_sort", referenced from:
      _nm_read_entire_thread in libnotmuch.a(mutt_notmuch.o)
      _get_query in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_status_to_string", referenced from:
      _nm_db_do_open in libnotmuch.a(nm_db.o)
  "_notmuch_tags_destroy", referenced from:
      _nm_get_all_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_tags_get", referenced from:
      _update_tags in libnotmuch.a(mutt_notmuch.o)
      _nm_get_all_tags in libnotmuch.a(mutt_notmuch.o)
      _update_email_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_tags_move_to_next", referenced from:
      _update_tags in libnotmuch.a(mutt_notmuch.o)
      _nm_get_all_tags in libnotmuch.a(mutt_notmuch.o)
      _update_email_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_tags_valid", referenced from:
      _update_tags in libnotmuch.a(mutt_notmuch.o)
      _nm_get_all_tags in libnotmuch.a(mutt_notmuch.o)
      _update_email_tags in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_thread_destroy", referenced from:
      _read_threads_query in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_thread_get_toplevel_messages", referenced from:
      _read_threads_query in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_threads_destroy", referenced from:
      _nm_message_is_still_queried in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_threads_get", referenced from:
      _read_threads_query in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_threads_move_to_next", referenced from:
      _read_threads_query in libnotmuch.a(mutt_notmuch.o)
  "_notmuch_threads_valid", referenced from:
      _read_threads_query in libnotmuch.a(mutt_notmuch.o)
      _nm_message_is_still_queried in libnotmuch.a(mutt_notmuch.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps to Reproduce

Summary of build options:

  Version:           20180716
  Host OS:           darwin18.6.0
  Install prefix:    /opt
  Compiler:           cc
  CFlags:            -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include -I/opt/include -DNCURSES_WIDECHAR
  LDFlags:           -L/opt/sdk/lib -L/var/sdk/lib -L/opt/lib -L/usr/local/lib -L/usr/lib -L/var/lib -L/lib -L. -L/opt/lib -L/opt/local/lib -L/opt/local/lib -dynamic -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err
  Libs:              -lkyotocabinet -lidn -lgnutls -lncursesw -lnotmuch -llua -lsasl2 -lgpgme  -lgpg-error -lintl -liconv
  Header cache libs: -lkyotocabinet

  GPGME:             yes
  PGP:               yes
  SMIME:             yes
  Notmuch:           yes
  Header Cache(s):   kyotocabinet
  Lua:               yes

$ git bisect bad

```
609cad0a92ff993389ac9ec6eae9160db28da6d5 is the first bad commit
commit 609cad0a92ff993389ac9ec6eae9160db28da6d5
Author: Richard Russon <rich@flatcap.org>
Date:   Sat Jul 7 12:02:05 2018 +0100

    create libnotmuch

:100644 100644 a6dc534784fb5c6d5986cbfe07c163a85297c95d 8dce07a1f0ca8bbc2c0de67c0923c1689df66c5f M	Makefile.autosetup
:100644 100644 49bf8cc4e336aa44407666f5d9d3f1f87447f3c6 e22e2743ed3aaa80db7866f66ec3f4f45beb60cf M	browser.c
:100644 100644 550555a89d50152cc35bf71ce9244c41e66d4303 c04e0504d574232b7662ca15d29215a7aff57650 M	buffy.c
:100644 100644 e19db60b590525f7dbd9057ab7d155fb6eb1d7a5 9a7377f0d2c21471e93d91e680dffae1bbb4a525 M	commands.c
:100644 100644 b58d39cbe7f9f1818025f0ca7df8d6f37ef34958 c786a953bc21708b466934b5f24ca09f47786c27 M	copy.c
:100644 100644 704afe6d05911c45bfde14044ecdf76f5a44895a 5fc5ea4dbdcea3606164416312b291123f140e70 M	curs_lib.c
:100644 100644 4f75221402a7560f91d00fd2cb31e20c73df2419 f1f60fa47e468bb01ac65d1a1fb190ef70a9765d M	curs_main.c
:100644 100644 cec49f7d54f98d9c002b67a4b5f9a30936f96b4a d2c3534456981a10e4163f878198f5408344049c M	init.c
:100644 100644 b4400e2e31c86bc473aeccd6ea036db2a5a8149d 5c05eb7a50c13ab7e52b9ce15e4c59c2ff8fdc42 M	mh.c
:100644 000000 2e31493fb316db1dc6b0d8b7956b28cc89499c20 0000000000000000000000000000000000000000 D	mutt_notmuch.c
:100644 000000 424fc35e61ac19ac979eb103ecc4bebf75a7559b 0000000000000000000000000000000000000000 D	mutt_notmuch.h
:100644 100644 8b00155897efabca68b2b14f9de8838e34054f0a f6900daca08c9623cb667fd710306b17aa208b61 M	mx.c
:000000 040000 0000000000000000000000000000000000000000 f60a4e06a68fa57ce2a040f16dbf21ba30095730 A	notmuch
:040000 040000 1c94924c37d0ca79c15ed2d8f2caba360b2ea379 2335436978eeef1c1902d416d287e7585280a1a7 M	po
:100644 100644 4d434f279a7bf1bde93851228867d63b6c1b231b 76756006f363088d538b4885265ef9a1be14f47c M	send.c
:100644 100644 9ff44f9516ac69aa94fc95670d516db257673943 829a2b5ae31452a343cea92cc05ac0e21b3794a8 M	sidebar.c
:100644 100644 6fb2f8a1e9296493f4784f7840f99cef890b849a 1f48b71a0fd86a6e1897f519245d7c6a11968e3e M	status.c
```

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

NeoMutt 20180716

## NeoMutt Version

```
commit b37a784d4fc6efe74c121c01408e6fdb9cbb93fd (HEAD -> master, origin/master, origin/HEAD)
Merge: d973635cc 8b9575c33
Author: Richard Russon <rich@flatcap.org>
Date:   Sun Jun 16 01:32:52 2019 +0100

    merge: upstream fixes
    
     * Improve imap_append_message() error message handling
     * Mention sources for ~p and ~P patterns
     * Allow imap_cmd_finish() to both expunge and fetch new mail
     * Improve $reverse_realname documentation
     * Add $fcc_before_send, defaulting unset
```

## Extra Info

Compiles without "--notmuch", but still suffers from https://github.com/neomutt/neomutt/issues/1629

* Operating System and its version

MacOS Mojave (10.14.5 )
MacPorts 2.5.4
notmuch @0.29_1

* Were you using multiple copies of NeoMutt at once?

no

* Were you using 'screen' or 'tmux'?

no

* Is your email local (maildir) or remote (IMAP)?

Neither, it's local (mbox)

**Comment by flatcap** [comment]
Hmm... I don't understand what's going wrong here.
The commit you bisected to simply moves `mutt_notmuch.c`, it doesn't change any build requirements.

Please can you quote me the last few lines of the build (just before all the errors).
My link line shows:
```
clang -o neomutt account.o addrbook.o alias.o bcache.o browser.o color.o commands.o complete.o compose.o compress.o conststrings.o context.o copy.o curs_lib.o edit.o editmsg.o enriched.o enter.o filter.o flags.o git_ver.o handler.o hdrline.o help.o hook.o index.o init.o keymap.o mailbox.o main.o menu.o muttlib.o mutt_account.o mutt_attach.o mutt_body.o mutt_header.o mutt_history.o mutt_logging.o mutt_parse.o mutt_signal.o mutt_socket.o mutt_thread.o mutt_window.o mx.o myvar.o neomutt.o pager.o pattern.o postpone.o progress.o query.o recvattach.o recvcmd.o resize.o rfc1524.o rfc3676.o score.o send.o sendlib.o sidebar.o smtp.o sort.o state.o status.o system.o terminal.o version.o icommands.o remailer.o mutt_lua.o monitor.o libpop.a libnntp.a libmbox.a libnotmuch.a libmaildir.a libncrypt.a libimap.a libconn.a libhcache.a libconfig.a libemail.a libaddress.a libmutt.a -L/usr/lib -L/lib -L/usr/lib/ -Wl,--as-needed -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err  -ltokyocabinet -lqdbm -lkyotocabinet -llmdb -lgdbm -ldb-5.3 -lidn2 -lgnutls -lncursesw -ltinfo -lnotmuch -llua-5.3 -lsasl2 -lgpgme -lanl  -lgpg-error
```

**Comment by hvkls** [comment]
# FYI, MacPorts notmuch has been updated @0.29.1_0. They install into /opt/local

neomutt$ uname -a
Darwin blackice 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
neomutt$ date
Sat Jun 22 20:10:26 CEST 2019
neomutt$ git pull
Already up to date.
neomutt$ make clean ; make distclean ; autoreconf --install --force ; ./configure --prefix=/opt --sysconfdir=/opt/etc --with-gpgme=/opt/local --notmuch --with-ui=ncurses --with-ncurses=/opt/local --enable-locales-fix --with-ssl=/opt/local --gpgme --gss --smime --gnutls --sasl --kyotocabinet --with-lua=/opt/local --enable-debug ; make all
# [...]
ranlib libmutt.a
cc -o neomutt account.o addrbook.o alias.o bcache.o browser.o color.o commands.o complete.o compose.o compress.o conststrings.o context.o copy.o curs_lib.o edit.o editmsg.o enriched.o enter.o filter.o flags.o git_ver.o handler.o hdrline.o help.o hook.o index.o init.o keymap.o mailbox.o main.o menu.o muttlib.o mutt_account.o mutt_attach.o mutt_body.o mutt_header.o mutt_history.o mutt_logging.o mutt_parse.o mutt_signal.o mutt_socket.o mutt_thread.o mutt_window.o mx.o myvar.o neomutt.o pager.o pattern.o postpone.o progress.o query.o recvattach.o recvcmd.o resize.o rfc1524.o rfc3676.o score.o send.o sendlib.o sidebar.o smtp.o sort.o state.o status.o system.o terminal.o version.o icommands.o mutt_lua.o libpop.a libnntp.a libmbox.a libnotmuch.a libmaildir.a libncrypt.a libimap.a libconn.a libhcache.a libconfig.a libemail.a libaddress.a libmutt.a -L/opt/sdk/lib -L/var/sdk/lib -L/opt/lib -L/usr/local/lib -L/usr/lib -L/var/lib -L/lib -L. -L/opt/lib -L/opt/local/lib -L/opt/local/lib -dynamic -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err  -lkyotocabinet -lidn -lgnutls -lncursesw -lnotmuch -llua -lsasl2 -lgpgme  -lgpg-error -lintl -liconv
ld: warning: directory not found for option '-L/opt/sdk/lib'
ld: warning: directory not found for option '-L/var/sdk/lib'
ld: warning: directory not found for option '-L/lib'
Undefined symbols for architecture x86_64:
  "_notmuch_database_begin_atomic", referenced from:
      _nm_db_trans_begin in libnotmuch.a(nm_db.o)
# [...]

**Comment by flatcap** [comment]
Ah, I see the problem.
The link line includes all the object files and all our libraries, including `libnotmuch.a`.
Then come the external libraries, including `-lnotmuch` which searches the link path for libraries.

Your link path includes `-L.`

We ask for `-lnotmuch` and it finds one in the current directory.

I don't know where the `-L.` is coming from -- I don't think it's our configure.
Remove that (or move it after the location of the real notmuch library), and your build will work.

P.S. `autoreconf --install --force` hasn't been necessary for nearly two years, since we dropped autoconf.

**Comment by hvkls** [comment]
Thanks! I did both: it works!

As to the slowness when opening mailboxes https://github.com/neomutt/neomutt/issues/1728 and maybe my own bogus new mailboxes problem https://github.com/neomutt/neomutt/issues/1629, I have run "neomutt -d2" with the freshly compiled version. I don't know if that's intended, but these messages keep repeating for over 22000 lines:

[2019-06-23 09:33:30]<M> mx_mbox_open() Reading /var/mail/andre...
[2019-06-23 09:33:30]<M> mutt_progress_update() Reading /var/mail/andre... 0
[2019-06-23 09:33:30]<2> parse_parameters() 'boundary=Apple-Mail-CA96B45D-A1C7-4CB7-BBC4-1178FC6D21AD'
[2019-06-23 09:33:30]<2> parse_parameters() parse_parameter: 'boundary' = 'Apple-Mail-CA96B45D-A1C7-  4CB7-BBC4-1178FC6D21AD'
[2019-06-23 09:33:30]<2> parse_parameters() 'charset=UTF-8; format=flowed'
[2019-06-23 09:33:30]<2> parse_parameters() parse_parameter: 'charset' = 'UTF-8'
[2019-06-23 09:33:30]<2> parse_parameters() parse_parameter: 'format' = 'flowed'
[2019-06-23 09:33:30]<2> parse_parameters() 'charset=utf-8'
[2019-06-23 09:33:30]<2> parse_parameters() parse_parameter: 'charset' = 'utf-8'
[2019-06-23 09:33:30]<2> parse_parameters() 'charset=utf-8'                                           [2019-06-23 09:33:30]<2> parse_parameters() parse_parameter: 'charset' = 'utf-8'
[2019-06-23 09:33:30]<2> parse_parameters() 'charset=utf-8'
[2019-06-23 09:33:30]<2> parse_parameters() parse_parameter: 'charset' = 'utf-8'
[2019-06-23 09:33:30]<2> parse_parameters() 'charset=utf-8'
[2019-06-23 09:33:30]<2> parse_parameters() parse_parameter: 'charset' = 'utf-8'
[2019-06-23 09:33:30]<2> parse_parameters() 'charset=utf-8'
[2019-06-23 09:33:30]<2> parse_parameters() parse_parameter: 'charset' = 'utf-8'
[2019-06-23 09:33:30]<2> parse_parameters() 'boundary="----=_Part_8549785_297322396.1539004849193"'
[...]

**Comment by flatcap** [comment]
> As to the slowness when opening mailboxes ...

Thanks, that sounds relevant.
I've cut'n'pasted the comment to the other issue.
